### ISSUE TITLE
Problems with create Incident

### ISSUE THREAD

**Issue by sychev-a-k** [Netflix/dispatch#201] opened 2020-04-03 10:28 UTC
Hello!
I have two questions. I cannot add Commander to incident when i create an incident.
![image](https://user-images.githubusercontent.com/29555052/78350517-0660fc00-75ae-11ea-997b-2d22272f3d54.png)
In my .env file I set INCIDENT_PLUGIN_CONTACT_SLUG to default. But i don't create some slack channel to converstaion. And i see in log this.
![image](https://user-images.githubusercontent.com/29555052/78350731-5770f000-75ae-11ea-9d8c-73793bb7c5a5.png)
Now I want to test the dispatch offline (without some plugins, such as Jira, slack, etc.). I just want to see the person who took the incident to work. How can i do this?

My second question. How i Can create Task? I don't have some button to create(

**Comment by sychev-a-k** [comment] 2020-04-05 14:21
When I create Incident i Have this error when i try to set INCIDENT_PLUGIN_CONTACT_SLUG=
![image](https://user-images.githubusercontent.com/29555052/78500892-d0647900-7761-11ea-9cb2-685a58815925.png)
How I can resolve this?

**Comment by mvilanova** [comment] 2020-04-06 16:54
@sychev-a-k what value are you specifying in env var `INCIDENT_PLUGIN_CONTACT_SLUG`? You should use `slack-contact`. Until we have another plugin for conversations, Slack is the only option available.

Regarding to your question about tasks, right now the only way to create them is by assigning a comment in the investigation document to one of the incident participants. We will probably add a button to the UI in the future.

**Comment by tomarv2** [comment] 2020-04-14 15:00
@mvilanova try this, looks like duplicate of : https://github.com/Netflix/dispatch-docker/issues/34

**Closed** 2020-05-05 20:40 UTC
