### ISSUE TITLE
still getting errors for install.sh

### ISSUE THREAD

**Issue by mindfunk** [Netflix/dispatch#135] opened 2020-03-20 21:25 UTC
Is there better forum for questions?

I'm sure there is an issue in my .env file, but I am not sure what setting causes this:

INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> e75e103693f2, Initial migration
INFO  [alembic.runtime.migration] Running upgrade e75e103693f2 -> d0501fc6be89, empty message
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1247, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "application" does not exist

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/dispatch", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.8/site-packages/dispatch/cli.py", line 811, in entrypoint
    dispatch_cli()
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))

**Comment by kevgliss** [comment] 2020-03-20 21:40
Are you running the install script from:

https://github.com/Netflix/dispatch-docker/blob/master/install.sh#L113 ? 

This doesn't seem like it would be an env issue, more likely that the database is in a weird state. Have you had to run the install multiple times?

**Comment by kevgliss** [comment] 2020-03-20 21:41
Actually this looks like a duplicate of #120

**Closed by kevgliss** 2020-03-20 21:41 UTC
