### ISSUE TITLE
Improve documentation about PKCE

### ISSUE THREAD

**Issue by gargrag** [Netflix/dispatch#492] opened 2020-07-08 22:32 UTC
Hi, we are trying to adopt the tool, and we are struggling trying to configure PKCE with google auth, PKCE it's kind of new, we may not be fully getting it. But is it possible that you guys can help us configure that, so that we can contribute to the docs?

The issue now, is that without an auth provider, the app is not usable. We also detected that may be an inconsistency between the docs and the code with [this env var](https://github.com/Netflix/dispatch/blob/65d706dbbf3664140e2557c7cd8bf6f4f5c22ede/src/dispatch/plugins/dispatch_core/plugin.py#L93)

I also asked on a separate [issue](https://github.com/Netflix/dispatch/issues/76#issuecomment-643521276), and I tried reading the docs, but is still not clear, and I think this may be the case for the majority of the users.

Thanks

**Comment by johnbuhay** [comment] 2020-07-09 13:53
Is anyone successfully using the PKCE plugin? We are getting 401 responses but no redirect or log detailing why. Here is what we have tried so far and what we have learned:

I have not confirmed yet what `Authorized redirect URIs` to list on the IDP side of things. Can you point us to this? What I have found is https://github.com/Netflix/dispatch/blob/355eb650c0cc47e6e7f451fe313e383da8d182e2/src/dispatch/static/dispatch/src/auth/pkceAuthProvider.js#L96

dispatch configuration
```
DISPATCH_AUTHENTICATION_PROVIDER_PKCE_JWKS=https://www.googleapis.com/oauth2/v3/certs
VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_PKCE_OPEN_ID_CONNECT=https://accounts.google.com/.well-known/openid-configuration
VUE_APP_DISPATCH_AUTHENTICATOIN_PROVIDER_PKCE_CLIENT_ID=<IDP generated>.apps.googleusercontent.com
```

According to the documentation `DISPATCH_AUTHENTICATION_PROVIDER_PKCE_JWK` is necessary.  I think you meant `DISPATCH_AUTHENTICATION_PROVIDER_PKCE_JWKS` and the type is incorrect/not specified? Although this URL is available in the `.well-known/openid-configuration` response
- https://hawkins.gitbook.io/dispatch/configuration/app#dispatch_authentication_provider_pkce_jwk-default-true
- https://github.com/Netflix/dispatch/search?q=DISPATCH_AUTHENTICATION_PROVIDER_PKCE_JWK&unscoped_q=DISPATCH_AUTHENTICATION_PROVIDER_PKCE_JWK

other resources:
- https://www.oauth.com/oauth2-servers/single-page-apps/
- https://developers.google.com/identity/protocols/oauth2/javascript-implicit-flow
- https://developers.google.com/identity/protocols/oauth2/web-server
- https://developers.google.com/identity/protocols/oauth2/openid-connect

**Comment by kevgliss** [comment] 2020-07-09 16:34
Unfortunately, I believe every IDP will be a little bit different. I haven't personally tried to integrate with the Google IDP itself (we have an internal IDP based on Ping) so I don't have _explicit_ directions however our hope is that in choosing PKCE as a standard we should be able to support any IDP that supports PKCE. 

A few thoughts:

@gargrag @johnbuhay -- Yes, you're correct, the docs should say `DISPATCH_AUTHENTICATION_PROVIDER_PKCE_JWKS` not `DISPATCH_AUTHENTICATION_PROVIDER_PKCE_JWK`. See [here](https://github.com/Netflix/dispatch/blob/develop/src/dispatch/config.py#L93)

As far as what redirectURI to list, it's up to your IDP what they allow, some allow wildcarding i.e. you could whitelist the root of the app `https://dispatch.example.net/*` others will require a known callback so you would use `https://dispatch.example.net/implicit/callback` that should then forward you along.

You said you're receiving a 401, are you being forwarded to your IDP provider? Somethings you could check:

Are you seeing successful requests to your openIdConnect issuer in your network tab? This call happends [here](https://github.com/Netflix/dispatch/blob/355eb650c0cc47e6e7f451fe313e383da8d182e2/src/dispatch/static/dispatch/src/auth/pkceAuthProvider.js#L43) 

If you are getting redirected to your IDP, are you getting a `code_verifier` query parameter back? This is a query parameter unique to PKCE, if not it could point to a configuration issue on the IDP. 

If it helps this is what the console looks like for a valid PKCE handshake:
![2020-07-09_09-33](https://user-images.githubusercontent.com/2262214/87066367-4ea04380-c1c7-11ea-8800-2e055cc6328d.png)

cc @willbengtson

**Comment by johnbuhay** [comment] 2020-07-09 18:02
No, we do not get redirected to the IDP 

I have verified the IDP configuration successfully using the `/implicit/callback`authorized_uri and https://github.com/aaronpk/pkce-vanilla-js 

*Note: wildcard substitution for paths are not supported by Google OAuth clients

<img width="1430" alt="Screen Shot 2020-07-09 at 1 47 59 PM" src="https://user-images.githubusercontent.com/6697003/87074294-a604da80-c1ec-11ea-93fb-5f51b17cc372.png">

**Comment by kevgliss** [comment] 2020-07-09 18:24
Can you set a breakpoint here:
https://github.com/Netflix/dispatch/blob/develop/src/dispatch/static/dispatch/src/router/index.js#L27

And verify that you're entering the PKCE auth flow?

**Comment by kevgliss** [comment] 2020-07-09 18:29
If you're building the JS app separately (i.e. not having the dispatch install do it for you). There are a few things you will have to do to get the var set correctly. Essentially you will need a `.env` available _at build time_ for the frontend (it needs to exist in that dir). See: https://github.com/Netflix/dispatch/blob/develop/src/dispatch/static/dispatch/.env.example_vue_app

It could be we also need to specify `VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_SLUG=dispatch-auth-provider-pkce` in that particular file (to trigger that auth flow).

**Comment by willbengtson** [comment] 2020-07-09 19:20
`VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_SLUG=dispatch-auth-provider-pkce` is needed and verified we use the `dispatch-auth-provider-pkce` plugin here

**Comment by johnbuhay** [comment] 2020-07-09 21:22
We are building using the provided Dockerfile. Adding the `.env` and updating the vars solved our issue where the PKCE flow was not being initiated. I missed that.

We now have a new issue where [process.env.VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_PKCE_OPEN_ID_CONNECT_URL](https://github.com/Netflix/dispatch/blob/3b17bffbacdb44be2220303574ad4c1848404a71/src/dispatch/static/dispatch/src/auth/pkceAuthProvider.js#L19) in the debugger is unknown and [AuthorizationServiceConfiguration](https://github.com/openid/AppAuth-JS/blob/3f7653427414cfe56aa8c3e748d3f63265766ce9/src/authorization_service_configuration.ts#L73) fails to build the url.

<img width="1412" alt="Screen Shot 2020-07-09 at 3 57 14 PM" src="https://user-images.githubusercontent.com/6697003/87088992-b70d1600-c203-11ea-9339-e59a1047c498.png">

Now,
    the `/.env` file looks like
```
DISPATCH_AUTHENTICATION_PROVIDER_SLUG="dispatch-auth-provider-pkce"
VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_PKCE_OPEN_ID_CONNECT_URL="https://accounts.google.com"
VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_PKCE_CLIENT_ID="<REDACTED>.apps.googleusercontent.com"
```


the `/src/dispatch/static/dispatch/.env` file looks like:
```
# Authentication
VUE_APP_DISPATCH_OPEN_ID_CONNECT_URL="https://accounts.google.com"
VUE_APP_DISPATCH_CLIENT_ID="<REDACTED>.apps.googleusercontent.com"
VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_SLUG="dispatch-auth-provider-pkce"
```

thanks for your help

**Comment by johnbuhay** [comment] 2020-07-09 21:33
So it seems we have an issue where at build time, [`process.env.VAR` is not being interpolated](https://cli.vuejs.org/guide/mode-and-env.html#using-env-variables-in-client-side-code).

Looking into
https://github.com/Netflix/dispatch/blob/develop/docker/Dockerfile#L92
https://github.com/Netflix/dispatch/blob/develop/setup.py

**Comment by kevgliss** [comment] 2020-07-09 21:58
I wonder if we're missing a COPY for the ENV file at some point. I would have thought this would be enough:

https://github.com/Netflix/dispatch/blob/develop/docker/Dockerfile#L89

**Comment by johnbuhay** [comment] 2020-07-09 22:43
I have discovered this [VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_PKCE_OPEN_ID_CONNECT](https://github.com/Netflix/dispatch/search?q=VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_PKCE_OPEN_ID_CONNECT&unscoped_q=VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_PKCE_OPEN_ID_CONNECT) is unused.

It should be: [VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_PKCE_OPEN_ID_CONNECT_URL](https://github.com/Netflix/dispatch/search?q=VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_PKCE_OPEN_ID_CONNECT_URL&unscoped_q=VUE_APP_DISPATCH_AUTHENTICATION_PROVIDER_PKCE_OPEN_ID_CONNECT_URL)

And the keys in [.env.example_vue_app](https://github.com/Netflix/dispatch/blob/develop/src/dispatch/static/dispatch/.env.example_vue_app) are only referenced in that file?
 https://github.com/Netflix/dispatch/blob/e6d3a3ee193e66201bfe8b0a462dea61b29c7993/src/dispatch/static/dispatch/.env.example_vue_app#L2-L3

**Comment by johnbuhay** [comment] 2020-07-09 22:48
> I wonder if we're missing a COPY for the ENV file at some point. I would have thought this would be enough:
> 
> https://github.com/Netflix/dispatch/blob/develop/docker/Dockerfile#L89

It is and to verify I added `RUN ls -lah /usr/src/dispatch/ && ls -lah /usr/src/dispatch/src/dispatch/static/dispatch/ && exit 1` to look for the `.env` during the build

**Comment by johnbuhay** [comment] 2020-07-10 16:57
Status update:

After baking the client_id and oidc_url into a new container we are triggering the pkce plugin and redirect to the IDP for login.
We now get stuck on the `/implicit/callback?...&prompt=consent`.

Furthermore it seems the [Google token retrieval requires client_secret](https://developers.google.com/identity/protocols/oauth2/native-app#exchange-authorization-code), and I do not see anywhere we are providing that to dispatch.

Otherwise, it seems we will need to author a plugin to work with Google IDP...
https://developers.google.com/identity/protocols/oauth2/javascript-implicit-flow#request-parameter-response_type

**Comment by kevgliss** [comment] 2020-07-10 17:11
We could add the ability to set the `client_secret` easily enough, according to the library we use to handle this flow (AppAuth) that "secret" isn't really a secret: https://github.com/openid/AppAuth-JS/issues/46

Again, each IDP is a bit different. If you do wish to go down the road of having a different auth flow, I would be happy to merge something in if it makes it easier for folks to use the app.

**Comment by johnbuhay** [comment] 2020-07-13 16:00
A few things to note

1 - I will try to get a PR merged in the [openid/appauth](https://github.com/openid/AppAuth-JS/blob/49a73540b915d45c0dac20afc9e5ef8db49bbe5c/src/token_request.ts#L27) library, that will probably take some time as other PR's seem to have stalled on the project. Currently, it is missing support for passing the optional `client_secret` to requests. I can understand why as the [RFC6749#section-4.1.3](https://tools.ietf.org/html/rfc6749#section-4.1.3) outlines.

2 - Creating Google OAuth credentials with Desktop type does not allow you to specify redirect_uri and are intentionally limited to `"redirect_uris": ["urn:ietf:wg:oauth:2.0:oob", "http://localhost"]`.

**Comment by johnbuhay** [comment] 2020-07-15 20:40
Status update...

I have updated a private copy of the PKCEAuthPlugin to include the clientSecret option as an item in `extras:{client_secret: xyz}` and now does retrieve tokens from Google using the implicit grant flow

This now stands out as not being a JWT for jwt-decode https://github.com/Netflix/dispatch/blob/develop/src/dispatch/static/dispatch/src/auth/pkceAuthProvider.js#L76

as this throws the error now https://github.com/auth0/jwt-decode/blob/f904effc98e7555609cc22b994df5e2a4cb25455/lib/index.js#L20

**Comment by mclueppers** [comment] 2020-07-28 14:59
@johnbuhay I'm trying to get Google OAuth2 working as well. Thanks for the advice so far. I got past successful login by changing `access_token` to ìd_token` in the application:
https://github.com/Netflix/dispatch/blob/develop/src/dispatch/static/dispatch/src/auth/pkceAuthProvider.js#L76 becomes `response.idToken` 

But now backend is failing authorisation with a valid JWT (verified signature etc. at jwt.io). I'm adding some debug logging to investigate further.

**Comment by mclueppers** [comment] 2020-07-28 16:22
Alright, I finally got Google auth working after setting `DISPATCH_JWT_AUDIENCE` and disabling `verify_at_hash` JWT decode option. By the looks of it Google is adding `at_hash` in the response. I'm now trying to store somehow `access_token` that's required to verify `at_hash`. Cookie seems the best approach so far.

**Comment by gargrag** [comment] 2020-08-19 19:37
@mclueppers Can you please describe the steps you took to make google auth work?

**Comment by mclueppers** [comment] 2020-08-20 13:54
@gargrag I've opened a PR #535 with the changes I had to make inside the application.

**Comment by gargrag** [comment] 2020-08-31 17:35
Thanks! @mclueppers It's working for me now. I think I'm going to implement this as a separate auth provider on our fork.

**Comment by mclueppers** [comment] 2020-09-07 11:21
> Thanks! @mclueppers It's working for me now. I think I'm going to implement this as a separate auth provider on our fork.

Great news. I'm waiting for the separate adapter, sounds like the best implementation approach.

**Comment by patcable** [comment] 2020-10-11 15:51
Just wanted to stop by and say this thread + PR #535 was indispensable in getting PKCE/OIDC working in my environment. I'll write up a blog post soon about it, but thanks for your help folks.

**Comment by kevgliss** [comment] 2020-10-13 18:01
Thanks to @patcable, I think we are in a better place re: pkce configuration. Closing this now, please open a new issue if you find any other gaps.

**Closed by kevgliss** 2020-10-13 18:01 UTC
